<?php 
// $Id: sogintegration.module

/**
* @file
* Custom hooks for SOG member signup/creation
*/

define("DASHBOARD_DIR", "/var/www/studieren-ohne-grenzen.org/dashboard");

/**
 * Hook into CiviCRM Contribution page (Online Mitgliederformular)
 */
function sogintegration_civicrm_postProcess($formName, &$form ) {
    if ($formName == "CRM_Contribute_Form_Contribution_Confirm" 
            && $form->_values['title'] == "Aktive Mitgliedschaft") {
        
        require_once DASHBOARD_DIR . '/vendor/autoload.php';
        require_once(DASHBOARD_DIR . '/app/config.php');

        // get parameters from form
        $firstName = t($form->_submitValues['first_name']);
        $lastName = t($form->_submitValues['last_name']);
        $email = t($form->_params['email-5']);
        $lokalgruppe = t($form->_params['custom_11']);

        $lokalgruppe = "lg_" . strtolower($lokalgruppe);

        $api = new SOG\Api\SogDashboardApi($dashboard_config);
        $username = $api->createUser($firstName, $lastName, $email, $lokalgruppe);
        
        drupal_set_message("Account '".$username."' erstellt");
    }
}
